### ISSUE TITLE
combine jitter and scatter plot

### ISSUE THREAD

**Issue by tischi** [hmbotelho/shinyHTM#3]
I was wondering whether we could have only one GUI item called Scatter-plot and then automatically make a jitter-plot if one of the axis is categorical (i.e. non-numeric).
What do you think?

From my experience this would be great  because much of the code you just have to duplicate for the jitter and scatter plot, which is very annoying.

**Comment by hmbotelho** [comment]
Great idea.
Just pushed that change to the repo.
Thanks!
