### ISSUE TITLE
Quality Control

### ISSUE THREAD

**Issue by tischi** [hmbotelho/shinyHTM#4]
I tried running the QC on Count_Nuclei using below data set, but I could not figure out whether it was actually doing something. I think we should give the user information such as I did in my version about how many rows failed due to which QC.  Could you add a text output? (just using print() statements as in the Click&View).

----

Treatment: Metadata_gene
Batch: Metadata_plate
Well coordinate: Metadata_wellnum
Position coordinate: Metadata_posnum

[images--EMBO_HTM_2014.zip](https://github.com/hmbotelho/shinyHTM/files/436502/images--EMBO_HTM_2014.zip)

**Comment by hmbotelho** [comment]
Done!
For the moment I made it output exactly the same text to both the R console and the html page.
Maybe I will try to do the same in the "normalization" and "treatment summary" parts...
