### ISSUE TITLE
sample data

### ISSUE THREAD

**Issue by tischi** [hmbotelho/shinyHTM#5]
I think we should provide a sample data set with images such that the click and view functionality can be tested. The images could be jpegs such that it would be much smaller. What about my data set from the EMBO course? It contains 4 replicates and clear mitotic phenotypes.
Shall I provide it?

**Comment by hmbotelho** [comment]
Hi Tischi,
Yes please. That would be great.
I updated the sample dataset in the repo but I think the EMBO dataset would be more interesting.

**Comment by hmbotelho** [comment]
Update: the repo now includes 2 datasets:
* _myplate_01_ (readme.md included)
* EMBO dataset
