### ISSUE TITLE
tab and csv

### ISSUE THREAD

**Issue by tischi** [hmbotelho/shinyHTM#6]
Would be good if we were able to read in both csv and tab delimited tables.
Best would be if the software autodetects...

**Comment by tischi** [comment]
and xls :-)

**Comment by hmbotelho** [comment]
Added csv + tab-delimited support.
Excel should be included in no time

**Comment by tischi** [comment]
nice. 
could you point me to the place in the code where you do this?
maybe i can copy it to the old version as well.

**Comment by imagejan** [comment]
@tischi https://github.com/hmbotelho/shinyHTM/commit/fc06476c80eced6cb9825aaf648d591fe3e930ca ?

**Comment by hmbotelho** [comment]
The app can now load *.csv, tab-separated files,  *.xls and *.xlsx. For Excel files only the first sheet is considered.

All of this is conveniently wrapped in function `read.HTMtable()`  [lines 11-43, file `functions.r`]
Requires package `xlsx`

The only argument this function takes is the full path name to the file. The file type is auto-detected and the function returns a data.frame containing the data in the file.

More file types can this way be supported in the future.

@tischi Feel free to use the code in HTM Explorer
