### ISSUE TITLE
installation did not work

### ISSUE THREAD

**Issue by tischi** [hmbotelho/shinyHTM#60]
There was a Mac ( MacOS 10.14.2 ) computer where the following did not work:

```
install.packages(c("shiny","shinyalert","plotly","shinyjs","xlsx"))
```
...it ran through but in the end, e.g., shiny was not installed.

We then tried running the installation one by one it worked better. 

But in the end we still got an error:

```
Warning: Error in : package or namespace load failed for ‘tcltk’:
 .onLoad failed in loadNamespace() for 'tcltk', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/tcltk/libs/tcltk.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/tcltk/libs/tcltk.so, 10): Library not loaded: /opt/X11/lib/libX11.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/tcltk/libs/tcltk.so
  Reason: image not found
  58: stop
  57: value[[3L]]
  56: tryCatchOne
  55: tryCatchList
  54: tryCatch
  53: library
  52: loadpackage [./functions.r#15]
Error : package or namespace load failed for ‘tcltk’:
 .onLoad failed in loadNamespace() for 'tcltk', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/tcltk/libs/tcltk.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/tcltk/libs/tcltk.so, 10): Library not loaded: /opt/X11/lib/libX11.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/tcltk/libs/tcltk.so
  Reason: image not found
```

I don't understand why it needs tcltk at all....

**Comment by ssgpers** [comment]
Seems it is a Mac issue. I also got it, but on Windows works correctly
There are some comments about Mac on R installation page https://cran.r-project.org/bin/macosx/, but I did not go through it yet.

**Comment by hmbotelho** [comment]
shinyHTM uses `tcltk` to display a "save as" dialog box after the calculation of summary data:

![image](https://user-images.githubusercontent.com/7735703/50281113-5b731000-0446-11e9-84b5-d0d16fd750d4.png)


I didn't manage to test shinyHTM on the MacOS version you mention, but on MacOS 16.7.0 I found it to work well. I installed `tcltk` manually, though. I also updated the readme file to include this step.

Can you see if installing `tcltk` solves the problem?
I will try to do some tests on MacOS 10

**Comment by hmbotelho** [comment]
As pointed out in the [link](https://cran.r-project.org/bin/macosx/) @ssgpers provided, the solution turned out to be:
- Reinstalling [XQuartz](https://www.xquartz.org/)
- Opening an XQuartz window
- Running R with the `r` command
- Running shinyHTM, as usual, with `library(shiny);runGitHub("shinyhtm", "hmbotelho")`

The readme file now recommends explicitly installing `tcltk` anyway.
Newer MacOS X are not affected.
