### ISSUE TITLE
Show line index upon hoveringmouse on the plot

### ISSUE THREAD

**Issue by ssgpers** [hmbotelho/shinyHTM#68]

**Comment by hmbotelho** [comment]
Is this what you requested? eff2101c884ebc70706eadd1482256c703f27feb

**Comment by ssgpers** [comment]
Yes,

I also changed table representation to find easier corresponding line
[5655f69](https://github.com/hmbotelho/shinyHTM/commit/5655f694d6e4c313c21e53095650f30e6d29c7f2)
Please feel free to close the issue if all fine with you
