### ISSUE TITLE
scatter plot bug

### ISSUE THREAD

**Issue by tischi** [hmbotelho/shinyHTM#7]
we plotted a numeric column against itself and it seemed to add some jitter to it.
this should not be i guess...

**Comment by hmbotelho** [comment]
This may be the case if there are NAs or missing data.
Currently, when a scatter plot is requested the algorithm checks if the X data is numeric. If yes -> scatter plot. If not -> jitter plot

**Comment by hmbotelho** [comment]
c34873bf6e37182eedf11267c74de5499dcef65b
