### ISSUE TITLE
Depending on number of channels images are shown differently.

### ISSUE THREAD

**Issue by ssgpers** [hmbotelho/shinyHTM#70]

**Comment by hmbotelho** [comment]
Fixed this in 03a49b14ae9fab2c3c32f1d07f29fd6584c5a693 

The behavior depends on the number of images associated to each data point:

- **1 image**: trivial
- **2-to-7 images**: open as multi-color composite
- **7+ images**: open as stack. ImageJ does not support 7+ color composites.

The vast majority of users will only be seeing uni- or multi-color images. Hardly anyone will have 7+ images (_i.e._ "channels") that they want to open simultaneously.

**Comment by ssgpers** [comment]
Cool. Thanks a lot!
I think we can close now this issue
