### ISSUE TITLE
Show image name as a title of image window

### ISSUE THREAD

**Issue by ssgpers** [hmbotelho/shinyHTM#71]

**Comment by hmbotelho** [comment]
I guess this issue applies only when opening more than just 1 image at a time (images open as a composite)

Which image (i.e. "channel") should provide the image title?

Assigning window titles is now straightforward: 03a49b14ae9fab2c3c32f1d07f29fd6584c5a693

**Comment by ssgpers** [comment]
Normally screen data have the same base, so does not really matter.
We can simply make first channel by default.

**Comment by hmbotelho** [comment]
Done! d5ad2f845dae4b9056139715ca806f04644a11b3

**Comment by ssgpers** [comment]
Great! Thanks, works for us. I close now
